### ISSUE TITLE
 Issue Template: Unable to Set Up Virtual Environment for Emulator Execution on macOS 14 GitHub Runner

### ISSUE THREAD

**Issue by mg3994** [FilledStacks/testsweets-example#2]
### Description:
The primary issue at hand is the inability to set up a virtual environment on the macOS 14 GitHub runner to run emulators. As of Now it is not Possible 

### Proposed Solution:
To address this issue, it's crucial to ensure compatibility with Intel-based CPUs by creating an executable for Intel systems. Please Check [FilledStacks/homebrew-tap](https://github.com/FilledStacks/homebrew-tap).

The repository mentioned provides an executable package that is identical for both Intel and ARM architectures. 
```rb
 on_macos do
    if Hardware::CPU.intel?
      url "https://firebasestorage.googleapis.com/v0/b/testsweets-38348.appspot.com/o/testsweets-dist.tar.gz?alt=media&token=c44d53b1-6cdc-4c6f-8175-c61769b0a39a"
      sha256 "4b84235fcbd08d90c729562650cefa0df7a19dccbc6d0181366cd077e41b4899"
    end

    if Hardware::CPU.arm?
      url "https://firebasestorage.googleapis.com/v0/b/testsweets-38348.appspot.com/o/testsweets-dist.tar.gz?alt=media&token=c44d53b1-6cdc-4c6f-8175-c61769b0a39a"
      sha256 "4b84235fcbd08d90c729562650cefa0df7a19dccbc6d0181366cd077e41b4899"
    end
  end
```
### Suggested Action:
* Release a new version of `testsweets` on Homebrew, explicitly stating compatibility with Intel-based systems.
* Utilize an Intel-based GitHub runner to execute emulators in the specified [workflow](https://github.com/FilledStacks/testsweets-example/blob/master/.github/workflows/main.yml)
* Consider adopting a naming convention for the packages to distinguish between Intel and ARM-based architectures (e.g., _macos_x86_64.tar.gz for Intel-based macOS and _macos_arm64.tar.gz for ARM-based macOS).

**Comment by mg3994** [comment]
I tried creating Android Emulator for different Mac Os version , But in my that case Mac Os 14 was failed to start Emulator, So I cancelled that Workflow Run , You can Check the that [Here](https://github.com/mg3994/moto_x4/actions/runs/8124574246)

**Comment by FilledStacks** [comment]
Yes, I will build this manually today and upload an intel version as well.

**Comment by mg3994** [comment]
Thanks, I am Waiting to test that workflow

**Comment by FilledStacks** [comment]
Formula updated
